### ISSUE TITLE
SyntaxError: Unexpected token o

### ISSUE THREAD

**Issue by Cryptophobia** [hoxxep/Gookie#2]
When I try to run I get the following error:
I tried to debug and run with many different versions of node but get the same error.

SyntaxError: Unexpected token o
    at Object.parse (native)
    at Gookie/gookie.js:181:36
    at Layer.handle [as handle_request](Gookie/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (Gookie/node_modules/express/lib/router/index.js:312:13)
    at Gookie/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (Gookie/node_modules/express/lib/router/index.js:330:12)
    at next (Gookie/node_modules/express/lib/router/index.js:271:10)
    at textParser (Gookie/node_modules/body-parser/lib/types/text.js:66:40)
    at Layer.handle [as handle_request](Gookie/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (Gookie/node_modules/express/lib/router/index.js:312:13)

**Comment by hoxxep** [comment]
Is this as soon as you start the app? It seems to be failing to parse the response body as JSON judging by the line `at Gookie/gookie.js:181:36`. I can't reproduce the error, would you be able to provide the JSON response it's receiving? (Add a `console.log` before line 181?).

**Comment by Cryptophobia** [comment]
Hi, I just figured out what I was doing wrong. I was testing it by sending wrong formatted http requests to the port and it was crashing the server because obviously JSON was not correct. I ran it today and configured a proper Github webhook and everything seems to works. I apologize for wasting your time and thank you for creating this awesome Nodejs webhook handler server.

Do you know if it would work with Github Enterprise? I noticed that formatUrl function is assuming github.com url. And after modifying it, could it work with Github Enterprise servers?

**Comment by Cryptophobia** [comment]
I just confirmed, it works with Github Enterprise.

**Comment by hoxxep** [comment]
Great to know it works with GitHub enterprise. No problem at all, glad it works, and thanks for using it!
